TieuLuan/Models/Delivery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.ImgDeliveries = new HashSet<ImgDelivery>();
        }
    
        public int DeliveryId { get; set; }
        public string DeliveryTitle { get; set; }
        public string DeliveryDetails { get; set; }
        public string DeliveryQuestion { get; set; }
        public string EmployeeCode { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgDelivery> ImgDeliveries { get; set; }
    }
}

TieuLuan/Areas/Admin/Controllers/DeliveriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TieuLuan.Models;
using System.IO;
namespace TieuLuan.Areas.Admin.Controllers
{
    public class DeliveriesController : BaseController
    {
        private CT464Entities db = new CT464Entities();

        // GET: Admin/Deliveries
        public ActionResult Index()
        {
            var deliveries = db.Deliveries.Include(d => d.Employee);
            return View(deliveries.ToList());
        }

        // GET: Admin/Deliveries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Delivery delivery = db.Deliveries.Find(id);
            if (delivery == null)
            {
                return HttpNotFound();
            }
            return View(delivery);
        }

        // GET: Admin/Deliveries/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "FirstName");
            return View();
        }

        // POST: Admin/Deliveries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DeliveryId,DeliveryTitle,DeliveryDetails,DeliveryQuestion,EmployeeCode")] Delivery delivery)
        {
            if (ModelState.IsValid)
            {
                db.Deliveries.Add(delivery);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "FirstName", delivery.EmployeeCode);
            return View(delivery);
        }

        // GET: Admin/Deliveries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Delivery delivery = db.Deliveries.Find(id);
            if (delivery == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "FirstName", delivery.EmployeeCode);
            return View(delivery);
        }

        // POST: Admin/Deliveries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DeliveryId,DeliveryTitle,DeliveryDetails,DeliveryQuestion,EmployeeCode")] Delivery delivery)
        {
            if (ModelState.IsValid)
            {
                db.Entry(delivery).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeCode = new SelectList(db.Employees, "EmployeeCode", "FirstName", delivery.EmployeeCode);
            return View(delivery);
        }

        // GET: Admin/Deliveries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Delivery delivery = db.Deliveries.Find(id);
            if (delivery == null)
            {
                return HttpNotFound();
            }
            return View(delivery);
        }

        // POST: Admin/Deliveries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Delivery delivery = db.Deliveries.Find(id);
            db.Deliveries.Remove(delivery);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Xử lý hình ảnh
        public ActionResult UploadDelivery(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var delivery = db.Deliveries
                .Include(s => s.ImgDeliveries)
                .SingleOrDefault(p => p.DeliveryId == id);
            if (delivery == null)
            {
                object err = "Thông tin truy cập không tồn tại!";
                return View("Error", err);
            }
            return View(delivery);
        }

        /// <summary>
        /// </summary>
        /// <param name="id">compare id of img with source</param>
        /// <param name="files">allow to upload file img</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UploadDelivery(int id, HttpPostedFileBase[] files)
        {
            byte max = 0;
            var listImg = db.ImgDeliveries.Where(p => p.DeliveryId == id).ToList();
            if (listImg.Count > 0)
                max = listImg.Max(p => p.SortDeli);
            var listFile = files.Where(p => p != null);
            foreach (var f in listFile)
            {
                var img = new ImgDelivery();
                img.DeliveryId = id;
                img.DeliveryImg = f.FileName;
                img.SortDeli = ++max;
                db.ImgDeliveries.Add(img);
                var path = Server.MapPath("~/ImgUI/Deli/" + f.FileName);
                f.SaveAs(path);
            }
            if (listFile.Any())
                db.SaveChanges();
            return RedirectToAction("UploadDelivery", new { id });
        }


        public ActionResult DeleteImg(int id, int? DeliveryId)
        {
            if (DeliveryId.HasValue)
            {
                try
                {
                    var img = db.ImgDeliveries.Find(id);
                    if (img == null)
                        return RedirectToAction("Index");
                    db.ImgDeliveries.Remove(img);
                    var fileName = img.DeliveryImg;
                    var path = Server.MapPath("~/ImgUI/Deli/" + fileName);
                    var file = new FileInfo(path);

                    if (file.Exists)
                    {
                        file.Delete();
                    }

                    db.SaveChanges();
                    return RedirectToAction("UploadDelivery");
                }

                catch (Exception ex)
                {
                    object mess = "Can not Delete IMG " + ex.Message;
                    return View("Error", mess);
                }
            }

            TempData["Success_Mess"] = "<script>alert('Delete Success')</script>";
            return Redirect("~/Deliveries/UploadDelivery/" + DeliveryId);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TieuLuan/Areas/Admin/Views/Deliveries/Create.cshtml
@model TieuLuan.Models.Delivery;

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Administrator.cshtml";
}

<h2 class=" text-center">Thêm Thông Tin Hỗ Trợ Khách Hàng</h2>
<div><a href="@Url.Action("Index","Deliveries")" class="btn btn-info">Quản lý</a></div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryQuestion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryQuestion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryQuestion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeCode, "EmployeeCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-info" />
            </div>
        </div>
    </div>
}

TieuLuan/Areas/Admin/Views/Deliveries/Delete.cshtml
@model TieuLuan.Models.Delivery

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Administrator.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delivery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeliveryTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryQuestion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryQuestion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.EmployeePass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.EmployeePass)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            <a href="@Url.Action("Index","Deliveries")" class="btn btn-info">Quản Lý</a>
        </div>
    }
</div>

TieuLuan/Areas/Admin/Views/Deliveries/Details.cshtml
@model TieuLuan.Models.Delivery

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Administrator.cshtml";
}

<h2 class="text-center">Thông Tin Hỗ Trợ Khách Hàng </h2>
<a href="@Url.Action("Index","Deliveries")" class="btn btn-info">Quản Lý</a>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeliveryTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryQuestion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryQuestion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "Deliveries", new { id = Model.DeliveryId })" class="btn btn-success">Chỉnh Sửa</a>
</p>

TieuLuan/Areas/Admin/Views/Deliveries/Edit.cshtml
@model TieuLuan.Models.Delivery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Administrator.cshtml";
}

<h2 class="text-center"> Chỉnh sửa thông tin danh mục</h2>
<div><a href="@Url.Action("Index","Deliveries")" class="btn btn-info">Quản lý</a></div>
@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DeliveryId)

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryQuestion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryQuestion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryQuestion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeCode, "EmployeeCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập Nhật" class="btn btn-info" />
            </div>
        </div>
    </div>
}

TieuLuan/Areas/Admin/Views/Deliveries/Index.cshtml
@model IEnumerable<TieuLuan.Models.Delivery>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Administrator.cshtml";
}

<h2 class="text-center">Thông Tin Hỗ Trợ</h2>

<p>
    <a href="@Url.Action("Create", "Deliveries")" class="btn btn-info">
        Tạo Mới
    </a>
</p>
<table class="table table-striped table-bordered" id="tablefillset">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDetails)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryQuestion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employee.FirstName)
            </th>
            <th></th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryDetails)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryQuestion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FirstName)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Deliveries", new { id = item.DeliveryId })" class="btn btn-success">
                        <i class="fa fa-flash"></i>
                        <span>

                        </span>
                    </a>
                    |
                    <a href="@Url.Action("UploadDelivery", "Deliveries", new { id = item.DeliveryId })" class="btn btn-default">
                        <i class=" fa fa-address-book-o"></i>
                        <span>

                        </span>
                    </a>
                    |
                    <a href="@Url.Action("Details", "Deliveries", new { id = item.DeliveryId })" class="btn btn-primary">
                        <i class="fa fa-list-alt"></i>
                        <span>

                        </span>
                    </a>
                    |
                    <a href="@Url.Action("Delete", "Deliveries", new { id = item.DeliveryId})" class="btn btn-danger">
                        <i class="fa fa-trash-o"></i>
                        <span>

                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

TieuLuan/Areas/Admin/Views/Deliveries/UploadDelivery.cshtml
@model TieuLuan.Models.Delivery

@{
    ViewBag.Title = "UploadDelivery";
    Layout = "~/Areas/Admin/Views/Shared/_Administrator.cshtml";
}

<h2 class=" text-center">Upload Hình Sản Phẩm</h2>
@using (Html.BeginForm("UploadDelivery", "Deliveries", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <article class="panel panel-info">
        @Html.HiddenFor(model => model.DeliveryId)
        <div class="panel-heading icon">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Mã</th>
                        <th>Tên Hình</th>
                        <th>Thứ Tự</th>
                        <th>Hình</th>
                        <th>Xóa</th>
                    </tr>
                </thead>
                @foreach (var item in @Model.ImgDeliveries)
                {

                    <tbody>
                        <tr>
                            <th>@item.DeliveryId</th>
                            <th>@item.DeliveryImg</th>
                            <th>@item.SortDeli</th>
                            <th><img src="~/ImgUI/Deli/@item.DeliveryImg" width="150" height="150" /></th>
                            <th>@Html.ActionLink("X", "DeleteImg", new { id = item.ImgDeliId, DeliveryId = item.DeliveryId }, htmlAttributes: new { onclick = "return confirm('Are you sure Delete Img?');", @class = "btn btn-circle brn-danger" })</th>
                        </tr>
                    </tbody>

                }
            </table>
        </div>
        <div class="panel-heading">

        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">File 1:</label>
                    <div class="col-md-10">
                        <input type="file" name="files" id="file1" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">File 2:</label>
                    <div class="col-md-10">
                        <input type="file" name="files" id="file2" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">File 3:</label>
                    <div class="col-md-10">
                        <input type="file" name="files" id="file3" class="form-control" />
                    </div>
                </div>
            </div>
            <input type="hidden" name="id" value="@Model.DeliveryId" id="spID" />
            <input type="submit" value="Upload" class="btn btn-primary btn-block" />
        </div>
    </article>


}